version: 2.1

executors:
  exectr:
    docker:
      - image: YourGitHubName/YourDockerRepoName:latest

jobs:
  build:
    executor: exectr
    steps:
      - checkout
      - run:
          name: Installing sudo
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing gcc
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install cmake
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Creating Build Files
          command: 'mkdir build && cd build && cmake ..'
      - run:
          name: Compile project
          command: 'cd build && make'
      - persist_to_workspace:
          root: .
          paths: build

  test:
    executor: exectr
    steps:
      - attach_work_space:
          at: .
      - run:
          name: Run ctest
          command: |
            cd build
            ctest
      - store_test_results:
          path: build

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
